### ISSUE TITLE
Cannot access a public repository

### ISSUE THREAD

**Issue by SallySchaffner** [SallySchaffner/Schaffner_ElapsedTime#1]
I am a teacher and I have asked my students to make their repositories public so I can view them. This is working fine for all but one student. When I try to access his public repository I get a 404 Page not found error. This happens with every repository he creates. We have verified that his repositories are public and are accessible to him on GitHub. Please provide insight as to why I cannot access the public repository for this one student. Here is an example URL: https://github.com/Mr-LeGendre/Test-Project-3.git

**Comment by DylanBT928** [comment]
Could it be an issue with his username? Searching up https://github.com/Mr-LeGendre/ does not work either.

**Comment by SallySchaffner** [comment]
That was probably the problem. The student changed his account to use his student username and now it is working. Thank you for responding.
